[env:jc3248w535c]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino

lib_deps =
    lvgl/lvgl @ ^8.3.11
    tzapu/WiFiManager @ ^2.0.17

build_flags =
    -mfix-esp32-psram-cache-issue
    -DLV_CONF_INCLUDE_SIMPLE
    -Isrc

upload_port = /dev/ttyACM0
upload_speed = 921600

monitor_port = /dev/ttyACM0
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
